### ISSUE TITLE
The AMD wrapper shim should be optional

### ISSUE THREAD

**Issue by mitermayer** [xquezme/gulp-dotjs-packer#2]
I have tried integrating with gulp-dotjs-packer on a library, the problem is i want all templates to be concatenated with the lib files but some of the applications that use the library have requirejs defined on the namespace, Which makes impossible to load the templates. The UMD wrapper should be an option and the default should be just a normal definition

```
(function() {
    var JST = JST || {};


   window.JST = JST;
}());
```

**Comment by mitermayer** [comment]
Added a PR for this issue https://github.com/xquezme/gulp-dotjs-packer/pull/3 left UMD as the default action for backwards compatibility

**Comment by xquezme** [comment]
Merged. Thanks.
